### ISSUE TITLE
Example script fails to load model 'test'

### ISSUE THREAD

**Issue by krother** [TJKessler/ECNet#2]
When running the example script in the README with the example config.yml and the shorter example table, I receive an error message. Here is the console session:

```krother@kristian-academis:~/ecn$ python run.py 
Build 1 of 1
Node 1 of 1
Trial 1 of 5
2017-09-12 09:21:11.125059: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-12 09:21:11.125094: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-12 09:21:11.125110: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Trial 2 of 5
Trial 3 of 5
Trial 4 of 5
Trial 5 of 5
Traceback (most recent call last):
  File "run.py", line 19, in <module>
    test_results = sv.use_mlp_model('test')	
  File "/home/krother/anaconda3/lib/python3.6/site-packages/ecnet/server.py", line 251, in use_mlp_model
    self.model.load_net(self.model_load_filename)
  File "/home/krother/anaconda3/lib/python3.6/site-packages/ecnet/model.py", line 137, in load_net
    self.layers = pickle.load(open("./" + model_load_filename + ".struct", "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './my_project/build_1/node_1/final_net_1.struct'
```

There are lots of other files that ECNet/TensorFlow generated:

```checkpoint
model_output_1.sess.data-00000-of-00001
model_output_1.sess.index
model_output_1.sess.meta
model_output_1.struct
model_output_2.sess.data-00000-of-00001
model_output_2.sess.index
model_output_2.sess.meta
model_output_2.struct
model_output_3.sess.data-00000-of-00001
model_output_3.sess.index
model_output_3.sess.meta
model_output_3.struct
model_output_4.sess.data-00000-of-00001
model_output_4.sess.index
model_output_4.sess.meta
model_output_4.struct
model_output_5.sess.data-00000-of-00001
model_output_5.sess.index
model_output_5.sess.meta
model_output_5.struct
```

**Comment by TJKessler** [comment]
Thank you for bringing this to our attention - "server.py" has been updated to handle this issue, as part of the v1.2.5.dev1 release.

**Comment by krother** [comment]
awesome, works!! (after a little fix to predict.py, see PullRequest)
